### ISSUE TITLE
Error when movie does exist but it does not have a poster

### ISSUE THREAD

**Issue by tsoernes** [misterhat/omdb#14]
Index.js line 250 please add this:
```
} else if (res.poster == null || res.poster == '') {
			out.emit('error', new Error("Movie found but it does not have a poster")); 
} else {
            req = needle.get(res.poster);
```
Because of this:
```
\node_modules\needle\lib\needle.js:81
      throw new TypeError('URL must be a string, not ' + uri);
            ^
TypeError: URL must be a string, not null
    at Object.Needle.request (\node
_modules\omdb\node_modules\needle\lib\needle.js:81:13)
    at Object.exports.(anonymous function) [as get] (\node_modules\omdb\node_modules\needle\lib\needle.js:425:19)
    at \node_modules\omdb\index.js:251:26
    at \node_modules\omdb\index.js:198:13
    at done (\node_modules\omdb\node_modules\needle\lib\needle.js:234:9)
    at PassThrough.<anonymous> (\node_modules\needle\lib\needle.js:363:11)
    at PassThrough.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```
Example movies: 
Bare 2015
Deadman Inferno 2015

**Comment by misterhat** [comment]
Fixed in https://github.com/misterhat/omdb/commit/2f86ba016874b4195ee3403568c94247a02c1712.
