### ISSUE TITLE
Cannot read property 'Response' of null

### ISSUE THREAD

**Issue by frenchie4111** [misterhat/omdb#20]
```
/Users/mike/Programming/personal/scripts/node_modules/omdb/index.js:224
        if (movie.Response === 'False') {
                 ^

TypeError: Cannot read property 'Response' of null
    at /Users/mike/Programming/personal/scripts/node_modules/omdb/index.js:224:18
    at done (/Users/mike/Programming/personal/scripts/node_modules/omdb/node_modules/needle/lib/needle.js:377:14)
    at PassThrough.<anonymous> (/Users/mike/Programming/personal/scripts/node_modules/omdb/node_modules/needle/lib/needle.js:576:9)
    at emitNone (events.js:72:20)
    at PassThrough.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

**Comment by misterhat** [comment]
Should be fixed in https://github.com/misterhat/omdb/commit/fae1e92e3773f34dea2c5fca191287b9f33b31c4
